apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: eventix
  labels:
    app: payment-service
    prometheus-scrape: "true"
spec:
  selector:
    app: payment-service
  ports:
    - port: 8085
      name: http
      targetPort: 8085
  type: ClusterIP
