apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: eventix
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/catalog_db"
  S3_BUCKET_NAME: "replace-with-terraform-output"
  AWS_REGION: "ap-south-1"
