apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: eventix
  labels:
    app: catalog-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: samarr30/catalog-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: catalog-service-config
            - secretRef:
                name: catalog-service-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 15
