apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: eventix
  labels:
    app: catalog-service
    prometheus-scrape: "true"
spec:
  selector:
    app: catalog-service
  ports:
    - port: 8082
      name: http
      targetPort: 8082
  type: ClusterIP
