server:
  port: 8084

spring:
  application:
    name: booking-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking_db}
    username: ${SPRING_DATASOURCE_USERNAME:eventix}
    password: ${SPRING_DATASOURCE_PASSWORD:eventix}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:dev-only-secret-please-change-me-before-any-real-deployment-32chars-min}

catalog:
  service:
    url: ${CATALOG_SERVICE_URL:http://catalog-service:8082}
inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://inventory-service:8083}
payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://payment-service:8085}
notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8086}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: booking-service
    distribution:
      percentiles-histogram:
        http.server.requests: true
